[build]
  command = "npm run build:react"
  publish = "build"
  
[build.environment]
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--no-audit --prefer-offline --no-fund"
  CI = "true"
  # Supabase Configuration for ScheduleBud
  # MOVED TO NETLIFY DASHBOARD FOR SECURITY:
  # REACT_APP_SUPABASE_URL = "your-supabase-url"
  # REACT_APP_SUPABASE_ANON_KEY = "your-supabase-anon-key"
  REACT_APP_BUILD_MODE = "saas"
  
  # SaaS Feature Flags
  REACT_APP_ENABLE_STRIPE = "true"
  REACT_APP_ENABLE_SUBSCRIPTIONS = "true"
  REACT_APP_ENABLE_USAGE_LIMITS = "true"
  REACT_APP_SHOW_UPGRADE_PROMPTS = "true"
  REACT_APP_SHOW_ANALYTICS = "true"
  REACT_APP_AI_CREDITS_LIMIT = "100"
  
  # Stripe Configuration for SaaS billing
  # MOVED TO NETLIFY DASHBOARD FOR SECURITY:
  # REACT_APP_STRIPE_PUBLISHABLE_KEY = "your-stripe-publishable-key"
  # REACT_APP_STRIPE_STUDENT_MONTHLY_PRICE_ID = "your-student-monthly-price-id"
  # REACT_APP_STRIPE_ACADEMIC_YEAR_PRICE_ID = "your-academic-year-price-id"

# SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers (matching Vercel config)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Static asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CSS/JS/Images/Fonts caching
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugin configuration disabled for troubleshooting
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Build processing configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true